name: Actualizar Calendario

on:
  schedule:
    - cron: '0 * * * *'  # Se ejecuta cada hora
  workflow_dispatch:  # Permite la ejecución manual desde la web de GitHub

jobs:
  generar_ical:
    runs-on: ubuntu-latest
    steps:
    - name: Clonar el repositorio
      uses: actions/checkout@v2

    - name: Configurar Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Instalar dependencias
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4 ics pytz

    - name: Ejecutar script
      run: python generar_calendario.py

    - name: Subir el archivo .ics
      uses: actions/upload-artifact@v2
      with:
        name: calendario
        path: spain_baloncesto.ics

    - name: Confirmar cambios en el repositorio
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "Actualizar calendario de partidos"
        file_pattern: 'spain_baloncesto.ics'
