name: Update Spain EuroBasket ICS
on:
  schedule:
    - cron: "*/30 10-22 * * *"   # cada 30 min de 12:00 a 24:00 CEST aprox (UTC en verano = +2)
  workflow_dispatch: {}
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install -r requirements.txt
      - run: python calendar.py
      - name: Commit updated ICS
        run: |
          git config user.name "calendar-bot"
          git config user.email "calendar-bot@users.noreply.github.com"
          git add spain-eurobasket.ics
          git commit -m "auto: update ICS" || echo "No changes"
          git push
